### ISSUE TITLE
Janti söz önerisi

### ISSUE THREAD

**Issue by PrensesMTN** [Janti-Sozler/janti-sozler.github.io#3]
Olmazlar oldu. Bu söz mü olmasın? 
Önerim: Güzel bir ölümü düşünecek kadar zamanın varsa neden sonuna kadar güzelce yaşamıyorsun?

**Comment by muaz742** [comment]
Öneri için teşekkür ederim. Janti söz eklendi 👍
https://github.com/Janti-Sozler/janti-sozler.github.io/commit/a772d9f4f2a052a126a1c09171b0f4352fe048ae
